// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKl--iCJ1U9hm2ZBpn-Wct-llEU3mMWGc',
    appId: '1:520937292678:web:844e0e7b25f45c2476e207',
    messagingSenderId: '520937292678',
    projectId: 'fibrohospital',
    authDomain: 'fibrohospital.firebaseapp.com',
    storageBucket: 'fibrohospital.appspot.com',
    measurementId: 'G-JM4RC0Y4PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wi8LPu4tIEYAZJgwFEQb65nW9MsQ-Ok',
    appId: '1:520937292678:android:3a8a326a33b458c776e207',
    messagingSenderId: '520937292678',
    projectId: 'fibrohospital',
    storageBucket: 'fibrohospital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvWnpQYr1LqxW_usnJJFCZt06kI4qQIU',
    appId: '1:520937292678:ios:db9c7eafeaff729276e207',
    messagingSenderId: '520937292678',
    projectId: 'fibrohospital',
    storageBucket: 'fibrohospital.appspot.com',
    iosBundleId: 'com.example.fibrohospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkvWnpQYr1LqxW_usnJJFCZt06kI4qQIU',
    appId: '1:520937292678:ios:db9c7eafeaff729276e207',
    messagingSenderId: '520937292678',
    projectId: 'fibrohospital',
    storageBucket: 'fibrohospital.appspot.com',
    iosBundleId: 'com.example.fibrohospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKl--iCJ1U9hm2ZBpn-Wct-llEU3mMWGc',
    appId: '1:520937292678:web:04fc3141ddc59f3a76e207',
    messagingSenderId: '520937292678',
    projectId: 'fibrohospital',
    authDomain: 'fibrohospital.firebaseapp.com',
    storageBucket: 'fibrohospital.appspot.com',
    measurementId: 'G-J63WQGZN27',
  );
}
